Change TCODLine implementation
libtcod/libtcod pull request #91
Opened 2021-04-14 22:36 UTC by sensualcoder

Updates TCODLine to be more idiomatic C++ style and replaces deprecated C function calls

2021-04-14 23:42 UTC, HexDecimal commented
I can't accept a PR that breaks ABI compatibility, but I'm open to a full rewrite of line handling as long the previous functions stay as they are.

I request that new C++ code is added as fully inline code in the `.h` headers.  Which is how the new C++ API is handled.

2021-04-14 23:50 UTC, HexDecimal commented
Honestly, I think every method of line drawing currently in libtcod has problems in both the C and C++ API.

2021-04-15 00:57 UTC, sensualcoder commented
Fair enough. I'll revert it to the old static functions and add a note to deprecate them, then add the updated functions.

I'll have a look around at the other line drawing code as well!

2021-04-15 01:29 UTC, sensualcoder commented
Woops, forgot to add documentation to the new functions.

2021-04-15 01:32 UTC, HexDecimal commented
I should explain better, or maybe I should make an issue to organize things.

Since line drawing is a pretty low-level task most of the code should be moved inline, even in C using C99 inline functions.  I haven't gotten used to how to implement these correctly.

For the callback-based functions.  The C callbacks need an additional userdata parameter to be useful.  C++ should support lambdas as callbacks.

C should have a function that outputs a full array of line indexes to a buffer.  C++ might use this function to return a std::vector of line coordinates.

C++ could have a dynamic iterator supporting ranged-based for loops to iterate over line coordinates without a heap buffer.

I'm not asking you to implement all of these, I'm just collecting my thoughts.

2021-04-15 01:43 UTC, HexDecimal commented
I recommend leaving `bresenham.cpp` and `bresenham.hpp` untouched.  New C++ code should be added to the end of `bresenham.h` in a block like this:

```cpp
#ifdef __cplusplus
namespace tcod {
// [new C++ API]
}  // namespace tcod
#endif  // __cplusplus
```
You should also leave the samples alone for now until the new API is decided on.

2021-04-15 02:26 UTC, sensualcoder commented
Is this more like what you were thinking?

2021-04-15 02:35 UTC, HexDecimal commented
> Is this more like what you were thinking?

Yes, you've understood me well so far.

> Thanks for the responses by the way, this is my first time ever contributing to anything open source.

You're doing pretty good.  This isn't an easy repository to contribute source changes to.

2021-04-15 02:44 UTC, HexDecimal requested changes

2021-04-15 02:44 UTC, HexDecimal commented on src/libtcod/bresenham.h
> +class TCODLIB_API Line {
Just `Line` might be to generic.  I might call this class `Bresenham` or `BresenhamLine` instead.

2021-04-15 02:44 UTC, HexDecimal commented on src/libtcod/bresenham.h
> +  static bool line(int xFrom, int yFrom, int xTo, int yTo, const std::function<bool(int, int)>& callback) {
This static method should be it's own separate function instead of inside the class.

2021-04-15 02:48 UTC, HexDecimal commented on src/libtcod/bresenham.h
> +  static bool line(int xFrom, int yFrom, int xTo, int yTo, const std::function<bool(int, int)>& callback) {
And again it would need a longer name mentioning `bresenham`.

2021-04-15 04:36 UTC, HexDecimal commented
The remaining issues would be the `#include` placement and the documentation (the functions need to be referenced from the docs directory, but that area is especially a mess.)  I feel like it might go smoother if I handled those instead of having you do them.

2021-04-15 04:39 UTC, sensualcoder commented
Should I put the cpp includes inside the first `#ifdef __cplusplus` block?

2021-04-15 05:14 UTC, HexDecimal commented
> Should I put the cpp includes inside the first `#ifdef __cplusplus` block, on line 37?

I usually put them in their own block, since in some cases you'd put regular C includes below them.

2021-04-15 06:33 UTC, HexDecimal commented
Anyway, if you don't want me to suddenly merge this then you should convert it into a draft.

2021-04-15 21:08 UTC, HexDecimal approved these changes

2021-04-16 05:07 UTC, merged

2021-04-16 05:10 UTC, HexDecimal commented
I've merged the changes although I'm still indecisive on what to do with them.  They'll at least be available provisionally for the moment.

I'm curious what setup you have to develop libtcod on.  Do you have any current projects using libtcod's C++ API?

2021-04-16 05:47 UTC, sensualcoder commented
I actually have been working on going through and updating the old C++
libtcod tutorial over on gitlab (
https://gitlab.com/libtcod-tutorials/libtcod-tutorials) while following the
newer Python tutorial. Which is what led me to update these in particular
since I had gotten to the part of the tutorial that uses them for map
creation.

On Fri, Apr 16, 2021, 12:11 AM Kyle Benesch ***@***.***>
wrote:

> I've merged the changes although I'm still indecisive on what to do with
> them. They'll at least be available provisionally for the moment.
>
> I'm curious what setup you have to develop libtcod on. Do you have any
> current projects using libtcod's C++ API?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/libtcod/libtcod/pull/91#issuecomment-820910001>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAL3GUYOJU4J6TMZ4KJ2UYLTI7BGZANCNFSM426IXIGA>
> .
>

2021-04-16 07:22 UTC, HexDecimal commented
Honestly the C++ API still needs a lot of work.  You seem to be better off than most others if you're willing to modify libtcod itself since the current API is not going to lead to clean C++ code.

I don't have any C++ projects of my own yet since I mostly prefer writing in Python.  It took a lot of work just to set up libtcod with a decent C/C++ package manager.  I've been trying to prepare [a template project](https://github.com/HexDecimal/libtcod-vcpkg-template) for this.

The new Python tutorial was mostly designed around Python.  I'm not sure how easy it will be to translate it back into C++.

2021-04-16 07:39 UTC, HexDecimal commented
I've raised issue #92 with more specifics on how I wanted line handling.  To me idiomatic C++ looks like this:
```cpp
for (auto&& [x, y] : tcod::bresenham({0, 0}, {4, 4})) {
  // ...
}
```

2021-04-16 15:53 UTC, sensualcoder commented
I definitely want to help update the C++ API since that's my language of choice, so I'm happy to start digging in wherever.

I've actually found it rather easy to look at the Python tutorial code and translate it some to C++, much more so than trying to update from the older C++ tutorial on roguebasin.